FIX #24653 modulebuilder: replace /myobject/ in includes
The templates view, like myobject_card.php are including the following
files:

    dol_include_once('/mymodule/class/myobject.class.php');
    dol_include_once('/mymodule/lib/mymodule_myobject.lib.php');

The mymodule value was replaced correctly, but the myobject value
wasn't, leading to another classfile beind included when, for instance,
creating new `myobject` objects (whatever myobject actually was, except
myobject of course), and resulting in PHP errors like:

     Fatal error: Uncaught Error: Class "DemoObject" not found in
     /var/www/html/custom/demobug/demoobject_card.php:105 Stack trace:
     #0 {main} thrown in
     /var/www/html/custom/demobug/demoobject_card.php on line 105

Fixes #24653